### ISSUE TITLE
Authentication - document and unitfy?

### ISSUE THREAD

**Issue by narve** [euniversal/umei-api-specification#82]
There should be a section on authentication (and possibly on authorization). 
If all implementors use the same authentication mechanism, that can be documented and added to the specification. 

In the NODES UMEI implementation we use the same authentication mechanism as for the non-UMEI implementation: 
OAuth based login flow (client credentials) to aquire a JWT token. This token is sent on each request as a "Bearer" token in the HTTP headers, like this: 

Authentication: Bearer eyJ... 

@cdmNSIDE How do you do authentication? 

@vladimirvrabely how about Centrica?

**Comment by vladimirvrabely** [comment]
We also use Oauth2 Client Credentials flow for authentication. We define additional `/token` endpoint where the users can get a bearer token with which they can make subsequent API requests.

**Comment by cdmNSIDE** [comment]
N-SIDE will also require to add a bearer token in each HTTP request. 
The JWT token will also contain a claim to specify the role of the user.

For the PT demo, those tokens will be directly sent to the different partners involved in the demo (E-REDES and Centrica) so that they can test and use the market platform.
We won't add any new endpoint in the market platform to acquire the token.
But I agree it would be the best solution, we simply won't do it for now for budget / timeline constraints.

I will read today the draft of D2.6 and check the part related to those aspects.
